### ISSUE TITLE
ENH: Use a faster t-SNE implementation

### ISSUE THREAD

**Issue by zoj613** [zoj613/pyloras#6]
Currently, scikit-learn's implementation is used. One of the following would likely perform better in terms of runtime:
- https://github.com/DmitryUlyanov/Multicore-TSNE
- https://github.com/pavlin-policar/openTSNE
- https://github.com/lvdmaaten/bhtsne

The current lines that would need to be changed are: 
https://github.com/zoj613/pyloras/blob/b896367dac4e970bb31d2b4cac69fe26f7627a2d/pyloras/_loras.py#L112-L115
https://github.com/zoj613/pyloras/blob/b896367dac4e970bb31d2b4cac69fe26f7627a2d/pyloras/_loras.py#L149

**Comment by santoshdvc** [comment]
Hi,
I found that out of the three  MultiCore-TSNE from  [https://github.com/DmitryUlyanov/Multicore-TSNE](https://github.com/DmitryUlyanov/Multicore-TSNE) is the fastest and relatively simple to use. It can directly replace `from sklearn.manifold import TSNE`. But there is an install error being faced while using pip to install MultiCore-TSNE.

```
Requirement already satisfied: numpy in c:\users\username\appdata\local\programs\python\python39\lib\site-packages (from MulticoreTSNE==0.1) (1.21.0)
Requirement already satisfied: cffi in c:\users\username\appdata\local\programs\python\python39\lib\site-packages (from MulticoreTSNE==0.1) (1.14.5)
Requirement already satisfied: pycparser in c:\users\username\appdata\local\programs\python\python39\lib\site-packages (from cffi->MulticoreTSNE==0.1) (2.20)
Building wheels for collected packages: MulticoreTSNE
  Building wheel for MulticoreTSNE (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\username\appdata\local\programs\python\python39\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\username\\AppData\\Local\\Temp\\pip-req-build-kpt7ghlg\\setup.py'"'"'; __file__='"'"'C:\\Users\\username\\AppData\\Local\\Temp\\pip-req-build-kpt7ghlg\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\username\AppData\Local\Temp\pip-wheel-69r1ew1b'
       cwd: C:\Users\username\AppData\Local\Temp\pip-req-build-kpt7ghlg\
  Complete output (28 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.9
  creating build\lib.win-amd64-3.9\MulticoreTSNE
  copying MulticoreTSNE\__init__.py -> build\lib.win-amd64-3.9\MulticoreTSNE
  creating build\lib.win-amd64-3.9\MulticoreTSNE\tests
  copying MulticoreTSNE\tests\test_base.py -> build\lib.win-amd64-3.9\MulticoreTSNE\tests
  copying MulticoreTSNE\tests\__init__.py -> build\lib.win-amd64-3.9\MulticoreTSNE\tests
  running egg_info
  creating MulticoreTSNE.egg-info
  writing MulticoreTSNE.egg-info\PKG-INFO
  writing dependency_links to MulticoreTSNE.egg-info\dependency_links.txt
  writing requirements to MulticoreTSNE.egg-info\requires.txt
  writing top-level names to MulticoreTSNE.egg-info\top_level.txt
  writing manifest file 'MulticoreTSNE.egg-info\SOURCES.txt'
  reading manifest file 'MulticoreTSNE.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'MulticoreTSNE.egg-info\SOURCES.txt'
  running build_ext
  cmake version 3.20.5

  CMake suite maintained and supported by Kitware (kitware.com/cmake).
  CMake Error: Unknown argument --
  CMake Error: Run 'cmake --help' for all supported options.

  ERROR: Cannot generate Makefile. See above errors.
  ----------------------------------------

```
In case, this error is negligible during actual implementation. Then I have changed the code accordingly to fit MultiCore-TSNE library.

**Comment by zoj613** [comment]
Hi @santoshdvc , thank you for your interest in this. Do you have benchmarks comparing the performance of the implementations ? Maybe you could use the example in the readme file to time them?

The faster TSNE implementation can be used as an optional package if available in the user's environment so it does not have to be installed with `pyloras` as part of its dependencies. However, the ease of installation will play a factor on which Tsne implementation should be favoured.

**Comment by santoshdvc** [comment]
Hi, 
I found the below benchmarks in the README of Multicore-TSNE and website of openTSNE. OpenTSNE scales over all and MultiCore TSNE atleast over `sklearn-TSNE` and `bhtsne`. I think the benchmarks were given valid.
![image](https://user-images.githubusercontent.com/41565795/125613016-3ed0c0b8-0b6e-441a-9cd9-47da01e24974.png)

![image](https://user-images.githubusercontent.com/41565795/125614598-5e360980-ac31-4887-be0b-06603a64d9f6.png)

Also, I found the installation of openTSNE packages is very simple and was achieved without any problems with single command,
```
pip install opentsne
```
I will go forward with the implementation of openTSNE.
I will keep it as an optional package, which will be automatically used if it is available in user's enviornment. Should I proceed like this?

**Comment by zoj613** [comment]
@santoshdvc  openTSNE sounds like the better choice here. A PR with the proposed change is welcome.

**Comment by zoj613** [comment]
@santoshdvc  Are you still interested in tackling this issue?

**Comment by santoshdvc** [comment]
@zoj613  Sorry, about it. I am totally engaged in some college activity.

**Comment by zoj613** [comment]
> @zoj613 Sorry, about it. I am totally engaged in some college activity.

No worries, I understand. I can leave it open for you if you want. It isn't particularly a high priority issue.
